[
    {
        "init": {
            "pre": {
                "AAAA": 0,
                "AAAC": 0,
                "AAAG": 0,
                "AAAT": 0,
                "AACA": 0,
                "AACC": 0,
                "AACG": 0,
                "AACT": 0,
                "AAGA": 0,
                "AAGC": 0,
                "AAGG": 0,
                "AAGT": 0,
                "AATA": 0,
                "AATC": 0,
                "AATG": 0,
                "AATT": 0,
                "ACAA": 0,
                "ACAC": 0,
                "ACAG": 0,
                "ACAT": 0,
                "ACCA": 0,
                "ACCC": 0,
                "ACCG": 0,
                "ACCT": 0,
                "ACGA": 0,
                "ACGC": 0,
                "ACGG": 0,
                "ACGT": 0,
                "ACTA": 0,
                "ACTC": 0,
                "ACTG": 0,
                "ACTT": 0,
                "AGAA": 0,
                "AGAC": 0,
                "AGAG": 0,
                "AGAT": 0,
                "AGCA": 0,
                "AGCC": 0,
                "AGCG": 0,
                "AGCT": 0,
                "AGGA": 0,
                "AGGC": 0,
                "AGGG": 0,
                "AGGT": 0,
                "AGTA": 0,
                "AGTC": 0,
                "AGTG": 0,
                "AGTT": 0,
                "ATAA": 0,
                "ATAC": 0,
                "ATAG": 0,
                "ATAT": 0,
                "ATCA": 0,
                "ATCC": 0,
                "ATCG": 0,
                "ATCT": 0,
                "ATGA": 0,
                "ATGC": 0,
                "ATGG": 0,
                "ATGT": 0,
                "ATTA": 0,
                "ATTC": 0,
                "ATTG": 0,
                "ATTT": 0,
                "CAAA": 0,
                "CAAC": 0,
                "CAAG": 0,
                "CAAT": 0,
                "CACA": 0,
                "CACC": 0,
                "CACG": 0,
                "CACT": 0,
                "CAGA": 0,
                "CAGC": 0,
                "CAGG": 0,
                "CAGT": 0,
                "CATA": 0,
                "CATC": 0,
                "CATG": 0,
                "CATT": 0,
                "CCAA": 0,
                "CCAC": 0,
                "CCAG": 0,
                "CCAT": 0,
                "CCCA": 0,
                "CCCC": 0,
                "CCCG": 0,
                "CCCT": 0,
                "CCGA": 0,
                "CCGC": 0,
                "CCGG": 0,
                "CCGT": 0,
                "CCTA": 0,
                "CCTC": 0,
                "CCTG": 0,
                "CCTT": 0,
                "CGAA": 0,
                "CGAC": 0,
                "CGAG": 0,
                "CGAT": 0,
                "CGCA": 0,
                "CGCC": 0,
                "CGCG": 0,
                "CGCT": 0,
                "CGGA": 0,
                "CGGC": 0,
                "CGGG": 0,
                "CGGT": 0,
                "CGTA": 0,
                "CGTC": 0,
                "CGTG": 0,
                "CGTT": 0,
                "CTAA": 0,
                "CTAC": 0,
                "CTAG": 0,
                "CTAT": 0,
                "CTCA": 0,
                "CTCC": 0,
                "CTCG": 0,
                "CTCT": 0,
                "CTGA": 0,
                "CTGC": 0,
                "CTGG": 0,
                "CTGT": 0,
                "CTTA": 0,
                "CTTC": 0,
                "CTTG": 0,
                "CTTT": 0,
                "GAAA": 0,
                "GAAC": 0,
                "GAAG": 0,
                "GAAT": 0,
                "GACA": 0,
                "GACC": 0,
                "GACG": 0,
                "GACT": 0,
                "GAGA": 0,
                "GAGC": 0,
                "GAGG": 0,
                "GAGT": 0,
                "GATA": 0,
                "GATC": 0,
                "GATG": 0,
                "GATT": 0,
                "GCAA": 0,
                "GCAC": 0,
                "GCAG": 0,
                "GCAT": 0,
                "GCCA": 0,
                "GCCC": 0,
                "GCCG": 0,
                "GCCT": 0,
                "GCGA": 0,
                "GCGC": 0,
                "GCGG": 0,
                "GCGT": 0,
                "GCTA": 0,
                "GCTC": 0,
                "GCTG": 0,
                "GCTT": 0,
                "GGAA": 1,
                "GGAC": 0,
                "GGAG": 1,
                "GGAT": 0,
                "GGCA": 0,
                "GGCC": 0,
                "GGCG": 0,
                "GGCT": 0,
                "GGGA": 2,
                "GGGC": 0,
                "GGGG": 0,
                "GGGT": 0,
                "GGTA": 0,
                "GGTC": 0,
                "GGTG": 0,
                "GGTT": 0,
                "GTAA": 0,
                "GTAC": 0,
                "GTAG": 0,
                "GTAT": 0,
                "GTCA": 0,
                "GTCC": 0,
                "GTCG": 0,
                "GTCT": 0,
                "GTGA": 0,
                "GTGC": 0,
                "GTGG": 0,
                "GTGT": 0,
                "GTTA": 0,
                "GTTC": 0,
                "GTTG": 0,
                "GTTT": 0,
                "TAAA": 0,
                "TAAC": 0,
                "TAAG": 0,
                "TAAT": 0,
                "TACA": 0,
                "TACC": 0,
                "TACG": 0,
                "TACT": 0,
                "TAGA": 0,
                "TAGC": 0,
                "TAGG": 0,
                "TAGT": 0,
                "TATA": 0,
                "TATC": 0,
                "TATG": 0,
                "TATT": 0,
                "TCAA": 0,
                "TCAC": 0,
                "TCAG": 0,
                "TCAT": 0,
                "TCCA": 0,
                "TCCC": 0,
                "TCCG": 0,
                "TCCT": 0,
                "TCGA": 0,
                "TCGC": 0,
                "TCGG": 0,
                "TCGT": 0,
                "TCTA": 0,
                "TCTC": 0,
                "TCTG": 0,
                "TCTT": 0,
                "TGAA": 0,
                "TGAC": 0,
                "TGAG": 0,
                "TGAT": 0,
                "TGCA": 0,
                "TGCC": 0,
                "TGCG": 0,
                "TGCT": 0,
                "TGGA": 0,
                "TGGC": 0,
                "TGGG": 0,
                "TGGT": 0,
                "TGTA": 0,
                "TGTC": 0,
                "TGTG": 0,
                "TGTT": 0,
                "TTAA": 0,
                "TTAC": 0,
                "TTAG": 0,
                "TTAT": 0,
                "TTCA": 0,
                "TTCC": 0,
                "TTCG": 0,
                "TTCT": 0,
                "TTGA": 0,
                "TTGC": 0,
                "TTGG": 0,
                "TTGT": 0,
                "TTTA": 0,
                "TTTC": 0,
                "TTTG": 0,
                "TTTT": 0
            },
            "start": {
                "AAA": 0,
                "AAC": 0,
                "AAG": 0,
                "AAT": 0,
                "ACA": 0,
                "ACC": 0,
                "ACG": 0,
                "ACT": 0,
                "AGA": 0,
                "AGC": 0,
                "AGG": 0,
                "AGT": 0,
                "ATA": 0,
                "ATC": 0,
                "ATG": 4,
                "ATT": 0,
                "CAA": 0,
                "CAC": 0,
                "CAG": 0,
                "CAT": 0,
                "CCA": 0,
                "CCC": 0,
                "CCG": 0,
                "CCT": 0,
                "CGA": 0,
                "CGC": 0,
                "CGG": 0,
                "CGT": 0,
                "CTA": 0,
                "CTC": 0,
                "CTG": 0,
                "CTT": 0,
                "GAA": 0,
                "GAC": 0,
                "GAG": 0,
                "GAT": 0,
                "GCA": 0,
                "GCC": 0,
                "GCG": 0,
                "GCT": 0,
                "GGA": 0,
                "GGC": 0,
                "GGG": 0,
                "GGT": 0,
                "GTA": 0,
                "GTC": 0,
                "GTG": 0,
                "GTT": 0,
                "TAA": 0,
                "TAC": 0,
                "TAG": 0,
                "TAT": 0,
                "TCA": 0,
                "TCC": 0,
                "TCG": 0,
                "TCT": 0,
                "TGA": 0,
                "TGC": 0,
                "TGG": 0,
                "TGT": 0,
                "TTA": 0,
                "TTC": 0,
                "TTG": 0,
                "TTT": 0
            },
            "aa1": {
                "AAA": 0,
                "AAC": 0,
                "AAG": 0,
                "AAT": 0,
                "ACA": 0,
                "ACC": 0,
                "ACG": 0,
                "ACT": 0,
                "AGA": 0,
                "AGC": 0,
                "AGG": 0,
                "AGT": 0,
                "ATA": 0,
                "ATC": 0,
                "ATG": 1,
                "ATT": 0,
                "CAA": 0,
                "CAC": 0,
                "CAG": 0,
                "CAT": 0,
                "CCA": 0,
                "CCC": 0,
                "CCG": 2,
                "CCT": 0,
                "CGA": 0,
                "CGC": 0,
                "CGG": 0,
                "CGT": 0,
                "CTA": 0,
                "CTC": 0,
                "CTG": 0,
                "CTT": 0,
                "GAA": 1,
                "GAC": 0,
                "GAG": 0,
                "GAT": 0,
                "GCA": 0,
                "GCC": 0,
                "GCG": 0,
                "GCT": 0,
                "GGA": 0,
                "GGC": 0,
                "GGG": 0,
                "GGT": 0,
                "GTA": 0,
                "GTC": 0,
                "GTG": 0,
                "GTT": 0,
                "TAA": 0,
                "TAC": 0,
                "TAG": 0,
                "TAT": 0,
                "TCA": 0,
                "TCC": 0,
                "TCG": 0,
                "TCT": 0,
                "TGA": 0,
                "TGC": 0,
                "TGG": 0,
                "TGT": 0,
                "TTA": 0,
                "TTC": 0,
                "TTG": 0,
                "TTT": 0
            }
        },
        "term": {
            "last": {
                "AAA": 0,
                "AAC": 0,
                "AAG": 0,
                "AAT": 0,
                "ACA": 0,
                "ACC": 0,
                "ACG": 0,
                "ACT": 0,
                "AGA": 0,
                "AGC": 0,
                "AGG": 0,
                "AGT": 0,
                "ATA": 0,
                "ATC": 0,
                "ATG": 0,
                "ATT": 0,
                "CAA": 0,
                "CAC": 0,
                "CAG": 0,
                "CAT": 0,
                "CCA": 0,
                "CCC": 0,
                "CCG": 0,
                "CCT": 0,
                "CGA": 0,
                "CGC": 0,
                "CGG": 0,
                "CGT": 0,
                "CTA": 0,
                "CTC": 0,
                "CTG": 0,
                "CTT": 0,
                "GAA": 0,
                "GAC": 0,
                "GAG": 0,
                "GAT": 0,
                "GCA": 0,
                "GCC": 0,
                "GCG": 0,
                "GCT": 0,
                "GGA": 0,
                "GGC": 0,
                "GGG": 0,
                "GGT": 0,
                "GTA": 0,
                "GTC": 0,
                "GTG": 0,
                "GTT": 0,
                "TAA": 0,
                "TAC": 0,
                "TAG": 0,
                "TAT": 0,
                "TCA": 0,
                "TCC": 0,
                "TCG": 0,
                "TCT": 0,
                "TGA": 0,
                "TGC": 0,
                "TGG": 0,
                "TGT": 0,
                "TTA": 0,
                "TTC": 0,
                "TTG": 0,
                "TTT": 0
            },
            "stop": {
                "AAA": 0,
                "AAC": 0,
                "AAG": 0,
                "AAT": 0,
                "ACA": 0,
                "ACC": 0,
                "ACG": 0,
                "ACT": 0,
                "AGA": 0,
                "AGC": 0,
                "AGG": 0,
                "AGT": 0,
                "ATA": 0,
                "ATC": 0,
                "ATG": 0,
                "ATT": 0,
                "CAA": 0,
                "CAC": 0,
                "CAG": 0,
                "CAT": 0,
                "CCA": 0,
                "CCC": 0,
                "CCG": 0,
                "CCT": 0,
                "CGA": 0,
                "CGC": 0,
                "CGG": 0,
                "CGT": 0,
                "CTA": 0,
                "CTC": 0,
                "CTG": 0,
                "CTT": 0,
                "GAA": 0,
                "GAC": 0,
                "GAG": 0,
                "GAT": 0,
                "GCA": 0,
                "GCC": 0,
                "GCG": 0,
                "GCT": 0,
                "GGA": 0,
                "GGC": 0,
                "GGG": 0,
                "GGT": 0,
                "GTA": 0,
                "GTC": 0,
                "GTG": 0,
                "GTT": 0,
                "TAA": 0,
                "TAC": 0,
                "TAG": 0,
                "TAT": 0,
                "TCA": 0,
                "TCC": 0,
                "TCG": 0,
                "TCT": 0,
                "TGA": 0,
                "TGC": 0,
                "TGG": 0,
                "TGT": 0,
                "TTA": 0,
                "TTC": 0,
                "TTG": 0,
                "TTT": 0
            },
            "suf": {
                "AAAA": 0,
                "AAAC": 0,
                "AAAG": 0,
                "AAAT": 0,
                "AACA": 0,
                "AACC": 0,
                "AACG": 0,
                "AACT": 0,
                "AAGA": 0,
                "AAGC": 0,
                "AAGG": 0,
                "AAGT": 0,
                "AATA": 0,
                "AATC": 0,
                "AATG": 0,
                "AATT": 0,
                "ACAA": 0,
                "ACAC": 0,
                "ACAG": 0,
                "ACAT": 0,
                "ACCA": 0,
                "ACCC": 0,
                "ACCG": 0,
                "ACCT": 0,
                "ACGA": 0,
                "ACGC": 0,
                "ACGG": 0,
                "ACGT": 0,
                "ACTA": 0,
                "ACTC": 0,
                "ACTG": 0,
                "ACTT": 0,
                "AGAA": 0,
                "AGAC": 0,
                "AGAG": 0,
                "AGAT": 0,
                "AGCA": 0,
                "AGCC": 0,
                "AGCG": 0,
                "AGCT": 0,
                "AGGA": 0,
                "AGGC": 0,
                "AGGG": 0,
                "AGGT": 0,
                "AGTA": 0,
                "AGTC": 0,
                "AGTG": 0,
                "AGTT": 0,
                "ATAA": 0,
                "ATAC": 0,
                "ATAG": 0,
                "ATAT": 0,
                "ATCA": 0,
                "ATCC": 0,
                "ATCG": 0,
                "ATCT": 0,
                "ATGA": 0,
                "ATGC": 0,
                "ATGG": 0,
                "ATGT": 0,
                "ATTA": 0,
                "ATTC": 0,
                "ATTG": 0,
                "ATTT": 0,
                "CAAA": 0,
                "CAAC": 0,
                "CAAG": 0,
                "CAAT": 0,
                "CACA": 0,
                "CACC": 0,
                "CACG": 0,
                "CACT": 0,
                "CAGA": 0,
                "CAGC": 0,
                "CAGG": 0,
                "CAGT": 0,
                "CATA": 0,
                "CATC": 0,
                "CATG": 0,
                "CATT": 0,
                "CCAA": 0,
                "CCAC": 0,
                "CCAG": 0,
                "CCAT": 0,
                "CCCA": 0,
                "CCCC": 0,
                "CCCG": 0,
                "CCCT": 0,
                "CCGA": 0,
                "CCGC": 0,
                "CCGG": 0,
                "CCGT": 0,
                "CCTA": 0,
                "CCTC": 0,
                "CCTG": 0,
                "CCTT": 0,
                "CGAA": 0,
                "CGAC": 0,
                "CGAG": 0,
                "CGAT": 0,
                "CGCA": 0,
                "CGCC": 0,
                "CGCG": 0,
                "CGCT": 0,
                "CGGA": 0,
                "CGGC": 0,
                "CGGG": 0,
                "CGGT": 0,
                "CGTA": 0,
                "CGTC": 0,
                "CGTG": 0,
                "CGTT": 0,
                "CTAA": 0,
                "CTAC": 0,
                "CTAG": 0,
                "CTAT": 0,
                "CTCA": 0,
                "CTCC": 0,
                "CTCG": 0,
                "CTCT": 0,
                "CTGA": 0,
                "CTGC": 0,
                "CTGG": 0,
                "CTGT": 0,
                "CTTA": 0,
                "CTTC": 0,
                "CTTG": 0,
                "CTTT": 0,
                "GAAA": 0,
                "GAAC": 0,
                "GAAG": 0,
                "GAAT": 0,
                "GACA": 0,
                "GACC": 0,
                "GACG": 0,
                "GACT": 0,
                "GAGA": 0,
                "GAGC": 0,
                "GAGG": 0,
                "GAGT": 0,
                "GATA": 0,
                "GATC": 0,
                "GATG": 0,
                "GATT": 0,
                "GCAA": 0,
                "GCAC": 0,
                "GCAG": 0,
                "GCAT": 0,
                "GCCA": 0,
                "GCCC": 0,
                "GCCG": 0,
                "GCCT": 0,
                "GCGA": 0,
                "GCGC": 0,
                "GCGG": 0,
                "GCGT": 0,
                "GCTA": 0,
                "GCTC": 0,
                "GCTG": 0,
                "GCTT": 0,
                "GGAA": 0,
                "GGAC": 0,
                "GGAG": 0,
                "GGAT": 0,
                "GGCA": 0,
                "GGCC": 0,
                "GGCG": 0,
                "GGCT": 0,
                "GGGA": 0,
                "GGGC": 0,
                "GGGG": 0,
                "GGGT": 0,
                "GGTA": 0,
                "GGTC": 0,
                "GGTG": 0,
                "GGTT": 0,
                "GTAA": 0,
                "GTAC": 0,
                "GTAG": 0,
                "GTAT": 0,
                "GTCA": 0,
                "GTCC": 0,
                "GTCG": 0,
                "GTCT": 0,
                "GTGA": 0,
                "GTGC": 0,
                "GTGG": 0,
                "GTGT": 0,
                "GTTA": 0,
                "GTTC": 0,
                "GTTG": 0,
                "GTTT": 0,
                "TAAA": 0,
                "TAAC": 0,
                "TAAG": 0,
                "TAAT": 0,
                "TACA": 0,
                "TACC": 0,
                "TACG": 0,
                "TACT": 0,
                "TAGA": 0,
                "TAGC": 0,
                "TAGG": 0,
                "TAGT": 0,
                "TATA": 0,
                "TATC": 0,
                "TATG": 0,
                "TATT": 0,
                "TCAA": 0,
                "TCAC": 0,
                "TCAG": 0,
                "TCAT": 0,
                "TCCA": 0,
                "TCCC": 0,
                "TCCG": 0,
                "TCCT": 0,
                "TCGA": 0,
                "TCGC": 0,
                "TCGG": 0,
                "TCGT": 0,
                "TCTA": 0,
                "TCTC": 0,
                "TCTG": 0,
                "TCTT": 0,
                "TGAA": 0,
                "TGAC": 0,
                "TGAG": 0,
                "TGAT": 0,
                "TGCA": 0,
                "TGCC": 0,
                "TGCG": 0,
                "TGCT": 0,
                "TGGA": 0,
                "TGGC": 0,
                "TGGG": 0,
                "TGGT": 0,
                "TGTA": 0,
                "TGTC": 0,
                "TGTG": 0,
                "TGTT": 0,
                "TTAA": 0,
                "TTAC": 0,
                "TTAG": 0,
                "TTAT": 0,
                "TTCA": 0,
                "TTCC": 0,
                "TTCG": 0,
                "TTCT": 0,
                "TTGA": 0,
                "TTGC": 0,
                "TTGG": 0,
                "TTGT": 0,
                "TTTA": 0,
                "TTTC": 0,
                "TTTG": 0,
                "TTTT": 0
            }
        },
        "entCDS": {
            "end2": {
                "AA": 0,
                "AC": 0,
                "AG": 0,
                "AT": 0,
                "CA": 0,
                "CC": 0,
                "CG": 0,
                "CT": 0,
                "GA": 3,
                "GC": 0,
                "GG": 7,
                "GT": 5,
                "TA": 0,
                "TC": 0,
                "TG": 0,
                "TT": 0
            },
            "first1": {
                "A": 4,
                "C": 2,
                "G": 6,
                "T": 3
            }
        },
        "outCDS": {
            "pre2": {
                "AA": 0,
                "AC": 0,
                "AG": 7,
                "AT": 3,
                "CA": 1,
                "CC": 0,
                "CG": 1,
                "CT": 0,
                "GA": 0,
                "GC": 0,
                "GG": 1,
                "GT": 1,
                "TA": 0,
                "TC": 0,
                "TG": 0,
                "TT": 1
            },
            "first2": {
                "AA": 0,
                "AC": 0,
                "AG": 0,
                "AT": 0,
                "CA": 0,
                "CC": 0,
                "CG": 0,
                "CT": 0,
                "GA": 0,
                "GC": 0,
                "GG": 0,
                "GT": 15,
                "TA": 0,
                "TC": 0,
                "TG": 0,
                "TT": 0
            },
            "next4": {
                "AAAA": 1,
                "AAAC": 0,
                "AAAG": 0,
                "AAAT": 0,
                "AACA": 0,
                "AACC": 0,
                "AACG": 0,
                "AACT": 0,
                "AAGA": 1,
                "AAGC": 0,
                "AAGG": 2,
                "AAGT": 1,
                "AATA": 0,
                "AATC": 0,
                "AATG": 0,
                "AATT": 0,
                "ACAA": 0,
                "ACAC": 0,
                "ACAG": 0,
                "ACAT": 0,
                "ACCA": 0,
                "ACCC": 0,
                "ACCG": 0,
                "ACCT": 0,
                "ACGA": 0,
                "ACGC": 0,
                "ACGG": 0,
                "ACGT": 0,
                "ACTA": 0,
                "ACTC": 0,
                "ACTG": 0,
                "ACTT": 0,
                "AGAA": 0,
                "AGAC": 0,
                "AGAG": 0,
                "AGAT": 0,
                "AGCA": 0,
                "AGCC": 0,
                "AGCG": 0,
                "AGCT": 0,
                "AGGA": 0,
                "AGGC": 0,
                "AGGG": 0,
                "AGGT": 0,
                "AGTA": 0,
                "AGTC": 0,
                "AGTG": 0,
                "AGTT": 0,
                "ATAA": 0,
                "ATAC": 0,
                "ATAG": 0,
                "ATAT": 0,
                "ATCA": 0,
                "ATCC": 0,
                "ATCG": 0,
                "ATCT": 0,
                "ATGA": 1,
                "ATGC": 0,
                "ATGG": 0,
                "ATGT": 0,
                "ATTA": 0,
                "ATTC": 0,
                "ATTG": 0,
                "ATTT": 0,
                "CAAA": 0,
                "CAAC": 0,
                "CAAG": 0,
                "CAAT": 0,
                "CACA": 0,
                "CACC": 0,
                "CACG": 0,
                "CACT": 0,
                "CAGA": 0,
                "CAGC": 0,
                "CAGG": 0,
                "CAGT": 0,
                "CATA": 0,
                "CATC": 0,
                "CATG": 0,
                "CATT": 0,
                "CCAA": 0,
                "CCAC": 0,
                "CCAG": 0,
                "CCAT": 0,
                "CCCA": 0,
                "CCCC": 0,
                "CCCG": 0,
                "CCCT": 0,
                "CCGA": 0,
                "CCGC": 0,
                "CCGG": 0,
                "CCGT": 0,
                "CCTA": 0,
                "CCTC": 0,
                "CCTG": 0,
                "CCTT": 0,
                "CGAA": 0,
                "CGAC": 0,
                "CGAG": 0,
                "CGAT": 0,
                "CGCA": 0,
                "CGCC": 0,
                "CGCG": 0,
                "CGCT": 0,
                "CGGA": 0,
                "CGGC": 0,
                "CGGG": 0,
                "CGGT": 0,
                "CGTA": 0,
                "CGTC": 0,
                "CGTG": 0,
                "CGTT": 0,
                "CTAA": 0,
                "CTAC": 0,
                "CTAG": 0,
                "CTAT": 0,
                "CTCA": 0,
                "CTCC": 0,
                "CTCG": 0,
                "CTCT": 0,
                "CTGA": 0,
                "CTGC": 0,
                "CTGG": 0,
                "CTGT": 0,
                "CTTA": 0,
                "CTTC": 0,
                "CTTG": 0,
                "CTTT": 0,
                "GAAA": 0,
                "GAAC": 0,
                "GAAG": 0,
                "GAAT": 0,
                "GACA": 0,
                "GACC": 0,
                "GACG": 0,
                "GACT": 0,
                "GAGA": 2,
                "GAGC": 2,
                "GAGG": 0,
                "GAGT": 4,
                "GATA": 0,
                "GATC": 0,
                "GATG": 0,
                "GATT": 0,
                "GCAA": 0,
                "GCAC": 0,
                "GCAG": 0,
                "GCAT": 0,
                "GCCA": 0,
                "GCCC": 0,
                "GCCG": 0,
                "GCCT": 0,
                "GCGA": 0,
                "GCGC": 0,
                "GCGG": 0,
                "GCGT": 0,
                "GCTA": 0,
                "GCTC": 0,
                "GCTG": 0,
                "GCTT": 0,
                "GGAA": 0,
                "GGAC": 0,
                "GGAG": 0,
                "GGAT": 0,
                "GGCA": 0,
                "GGCC": 0,
                "GGCG": 0,
                "GGCT": 0,
                "GGGA": 0,
                "GGGC": 0,
                "GGGG": 1,
                "GGGT": 0,
                "GGTA": 0,
                "GGTC": 0,
                "GGTG": 0,
                "GGTT": 0,
                "GTAA": 0,
                "GTAC": 0,
                "GTAG": 0,
                "GTAT": 0,
                "GTCA": 0,
                "GTCC": 0,
                "GTCG": 0,
                "GTCT": 0,
                "GTGA": 0,
                "GTGC": 0,
                "GTGG": 0,
                "GTGT": 0,
                "GTTA": 0,
                "GTTC": 0,
                "GTTG": 0,
                "GTTT": 0,
                "TAAA": 0,
                "TAAC": 0,
                "TAAG": 0,
                "TAAT": 0,
                "TACA": 0,
                "TACC": 0,
                "TACG": 0,
                "TACT": 0,
                "TAGA": 0,
                "TAGC": 0,
                "TAGG": 0,
                "TAGT": 0,
                "TATA": 0,
                "TATC": 0,
                "TATG": 0,
                "TATT": 0,
                "TCAA": 0,
                "TCAC": 0,
                "TCAG": 0,
                "TCAT": 0,
                "TCCA": 0,
                "TCCC": 0,
                "TCCG": 0,
                "TCCT": 0,
                "TCGA": 0,
                "TCGC": 0,
                "TCGG": 0,
                "TCGT": 0,
                "TCTA": 0,
                "TCTC": 0,
                "TCTG": 0,
                "TCTT": 0,
                "TGAA": 0,
                "TGAC": 0,
                "TGAG": 0,
                "TGAT": 0,
                "TGCA": 0,
                "TGCC": 0,
                "TGCG": 0,
                "TGCT": 0,
                "TGGA": 0,
                "TGGC": 0,
                "TGGG": 0,
                "TGGT": 0,
                "TGTA": 0,
                "TGTC": 0,
                "TGTG": 0,
                "TGTT": 0,
                "TTAA": 0,
                "TTAC": 0,
                "TTAG": 0,
                "TTAT": 0,
                "TTCA": 0,
                "TTCC": 0,
                "TTCG": 0,
                "TTCT": 0,
                "TTGA": 0,
                "TTGC": 0,
                "TTGG": 0,
                "TTGT": 0,
                "TTTA": 0,
                "TTTC": 0,
                "TTTG": 0,
                "TTTT": 0
            }
        }
    },
    {
        "init": {
            "correct": [
                [
                    "GGAG",
                    "ATG",
                    "ATG"
                ],
                [
                    "GGAA",
                    "ATG",
                    "GAA"
                ],
                [
                    "GGGA",
                    "ATG",
                    "CCG"
                ],
                [
                    "GGGA",
                    "ATG",
                    "CCG"
                ]
            ],
            "wrong": [
                [
                    "GGGA",
                    "GAT",
                    "GAT"
                ],
                [
                    "GAGA",
                    "TGA",
                    "TGG"
                ],
                [
                    "GGGA",
                    "AAT",
                    "GGA"
                ],
                [
                    "GAAA",
                    "TGG",
                    "AAA"
                ],
                [
                    "CGGG",
                    "AAT",
                    "GCC"
                ],
                [
                    "GGAA",
                    "TGC",
                    "CGA"
                ],
                [
                    "CGGG",
                    "AAT",
                    "GCC"
                ],
                [
                    "GGAA",
                    "TGC",
                    "CGA"
                ]
            ]
        },
        "term": {
            "correct": [],
            "wrong": []
        },
        "entCDS": {
            "correct": [
                [
                    0.6923076923076923,
                    "GG",
                    "A"
                ],
                [
                    0.9230769230769231,
                    "GG",
                    "T"
                ],
                [
                    0.7692307692307693,
                    "GT",
                    "G"
                ],
                [
                    0.8461538461538461,
                    "GA",
                    "T"
                ],
                [
                    0.6923076923076923,
                    "GG",
                    "A"
                ],
                [
                    0.6923076923076923,
                    "GT",
                    "T"
                ],
                [
                    0.8461538461538461,
                    "GG",
                    "G"
                ],
                [
                    0.6923076923076923,
                    "GT",
                    "A"
                ],
                [
                    0.8461538461538461,
                    "GG",
                    "A"
                ],
                [
                    0.6923076923076923,
                    "GA",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "GT",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "GG",
                    "C"
                ],
                [
                    0.6923076923076923,
                    "GA",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "GT",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "GG",
                    "C"
                ]
            ],
            "wrong": [
                [
                    0.7692307692307693,
                    "AG",
                    "G"
                ],
                [
                    0.6923076923076923,
                    "GA",
                    "A"
                ],
                [
                    1.0,
                    "AG",
                    "G"
                ],
                [
                    0.8461538461538461,
                    "GT",
                    "T"
                ],
                [
                    0.8461538461538461,
                    "AG",
                    "T"
                ],
                [
                    0.6923076923076923,
                    "TG",
                    "C"
                ],
                [
                    0.8461538461538461,
                    "AG",
                    "A"
                ],
                [
                    0.7692307692307693,
                    "AT",
                    "A"
                ],
                [
                    0.7692307692307693,
                    "AG",
                    "G"
                ],
                [
                    0.6153846153846154,
                    "GA",
                    "G"
                ],
                [
                    0.6923076923076923,
                    "AG",
                    "T"
                ],
                [
                    0.6153846153846154,
                    "TT",
                    "G"
                ],
                [
                    0.9230769230769231,
                    "AG",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "GG",
                    "A"
                ],
                [
                    0.6923076923076923,
                    "AG",
                    "T"
                ],
                [
                    0.6153846153846154,
                    "TA",
                    "C"
                ],
                [
                    0.8461538461538461,
                    "AG",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "GA",
                    "C"
                ],
                [
                    0.7692307692307693,
                    "AG",
                    "A"
                ],
                [
                    0.6153846153846154,
                    "AG",
                    "C"
                ],
                [
                    0.8461538461538461,
                    "AG",
                    "T"
                ],
                [
                    0.6923076923076923,
                    "TG",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "AG",
                    "G"
                ],
                [
                    0.6923076923076923,
                    "GC",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "AG",
                    "A"
                ],
                [
                    0.6153846153846154,
                    "AG",
                    "C"
                ],
                [
                    0.8461538461538461,
                    "AG",
                    "T"
                ],
                [
                    0.6923076923076923,
                    "TG",
                    "G"
                ],
                [
                    0.7692307692307693,
                    "AG",
                    "G"
                ],
                [
                    0.6923076923076923,
                    "GC",
                    "G"
                ]
            ]
        },
        "outCDS": {
            "correct": [
                [
                    "AG",
                    "GT",
                    "GGGG"
                ],
                [
                    "GG",
                    "GT",
                    "ATGA"
                ],
                [
                    "AT",
                    "GT",
                    "GAGC"
                ],
                [
                    "GT",
                    "GT",
                    "GAGT"
                ],
                [
                    "CA",
                    "GT",
                    "AAGT"
                ],
                [
                    "CG",
                    "GT",
                    "AAGA"
                ],
                [
                    "AG",
                    "GT",
                    "AAAA"
                ],
                [
                    "TT",
                    "GT",
                    "GAGT"
                ],
                [
                    "AG",
                    "GT",
                    "GAGC"
                ],
                [
                    "AG",
                    "GT",
                    "AAGG"
                ],
                [
                    "AT",
                    "GT",
                    "GAGT"
                ],
                [
                    "AG",
                    "GT",
                    "GAGA"
                ],
                [
                    "AG",
                    "GT",
                    "AAGG"
                ],
                [
                    "AT",
                    "GT",
                    "GAGT"
                ],
                [
                    "AG",
                    "GT",
                    "GAGA"
                ]
            ],
            "wrong": [
                [
                    "CA",
                    "GG",
                    "TGGG"
                ],
                [
                    "GG",
                    "TG",
                    "GGGC"
                ],
                [
                    "TG",
                    "GG",
                    "TATG"
                ],
                [
                    "GG",
                    "TA",
                    "TGAG"
                ],
                [
                    "CA",
                    "TG",
                    "TGAG"
                ],
                [
                    "TG",
                    "TG",
                    "AGCT"
                ],
                [
                    "GG",
                    "TG",
                    "TGAG"
                ],
                [
                    "TG",
                    "TG",
                    "AGTG"
                ],
                [
                    "GC",
                    "AG",
                    "TAAG"
                ],
                [
                    "AG",
                    "TA",
                    "AGTA"
                ],
                [
                    "AC",
                    "GG",
                    "TAAG"
                ],
                [
                    "GG",
                    "TA",
                    "AGAC"
                ],
                [
                    "AA",
                    "GG",
                    "TAAA"
                ],
                [
                    "GG",
                    "TA",
                    "AAAA"
                ],
                [
                    "CT",
                    "TG",
                    "TGAG"
                ],
                [
                    "TG",
                    "TG",
                    "AGTT"
                ],
                [
                    "AA",
                    "GG",
                    "TGAG"
                ],
                [
                    "GG",
                    "TG",
                    "AGCA"
                ],
                [
                    "CA",
                    "GG",
                    "TAAG"
                ],
                [
                    "GG",
                    "TA",
                    "AGGG"
                ],
                [
                    "GA",
                    "TG",
                    "TGAG"
                ],
                [
                    "TG",
                    "TG",
                    "AGTG"
                ],
                [
                    "TA",
                    "GG",
                    "TGAG"
                ],
                [
                    "GG",
                    "TG",
                    "AGAC"
                ],
                [
                    "CA",
                    "GG",
                    "TAAG"
                ],
                [
                    "GG",
                    "TA",
                    "AGGG"
                ],
                [
                    "GA",
                    "TG",
                    "TGAG"
                ],
                [
                    "TG",
                    "TG",
                    "AGTG"
                ],
                [
                    "TA",
                    "GG",
                    "TGAG"
                ],
                [
                    "GG",
                    "TG",
                    "AGAC"
                ]
            ]
        }
    }
]